In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


In [ ]:
#import the dataset that is to be used for training and testing
df = pd.read_excel("/content/drive/My Drive/Dropoutdataset.xlsx")
df.head()

Marital status  Application mode  Application order  Course  \
0               1                 8                  5       2   
1               1                 6                  1      11   
2               1                 1                  5       5   
3               1                 8                  2      15   
4               2                12                  1       3   

   Daytime/evening attendance  Previous qualification  Nacionality  \
0                           1                       1            1   
1                           1                       1            1   
2                           1                       1            1   
3                           1                       1            1   
4                           0                       1            1   

   Mother's qualification  Father's qualification  Mother's occupation  ...  \
0                      13                      10                    6  ...   
1                       1                       3                    4  ...   
2                      22                      27                   10  ...   
3                      23                      27                    6  ...   
4                      22                      28                   10  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    6   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 35 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance                      4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Nacionality                                     4424 non-null   int64  
 7   Mother's qualification                          4424 non-null   int64  
 8   Father's qualification                          4424 non-null   int64  
 9   Mother's occupation                      

In [ ]:
import pandas as pd

# Assuming df is your DataFrame
missing_values = df.isnull().sum()
print(missing_values)


Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular u

In [ ]:
#check for unique values in the target column to get to know how we will encode them / assign them numerical values
unique_values = df['Target'].unique()
unique_values

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

what is categorical and non categorical data?

how to handle categorical data

what is one hot encoding

what is encoding

In [ ]:
type(df) #checking kind of type our data is wether its pandas or numpy which stands for numerical python.

pandas.core.frame.DataFrame

In [ ]:
df = df.iloc[:,:].values

The code snippet df = df.iloc[:,:].values appears to be related to working with a DataFrame using the pandas library in Python. Let me break down what this line of code is doing:

df: This presumably represents a DataFrame object, which is a two-dimensional, tabular data structure commonly used in pandas.

.iloc: This is a method in pandas used for integer-location based indexing. It is commonly used to select rows and columns by their integer position.

[:,:]: This part specifies the range of rows and columns to be selected. The : symbol is used to indicate that we want to select all rows and columns.

.values: This is used to retrieve the values of the selected rows and columns as a NumPy array. When you use .values on a DataFrame, it returns the underlying data as a NumPy array.

In [ ]:
df

array([[1, 8, 5, ..., 1.4, 1.74, 'Dropout'],
       [1, 6, 1, ..., -0.3, 0.79, 'Graduate'],
       [1, 1, 5, ..., 1.4, 1.74, 'Dropout'],
       ...,
       [1, 1, 1, ..., -0.3, 0.79, 'Dropout'],
       [1, 1, 1, ..., -0.8, -3.12, 'Graduate'],
       [1, 5, 1, ..., 3.7, -1.7, 'Graduate']], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

The code from sklearn.preprocessing import LabelEncoder imports the LabelEncoder class from the sklearn.preprocessing module in scikit-learn, a popular machine learning library in Python.

The LabelEncoder is used for encoding categorical (non-numeric) labels into numeric labels. In machine learning, many algorithms require input data to be in numerical format. Categorical variables, such as class labels, need to be converted into numerical representations for these algorithms to work effectively.

In [ ]:
university = LabelEncoder()

In [ ]:
#applying the label encoder to the target column

df [:,34] = university.fit_transform(df[:,34])

In [ ]:
#check for the updates
df

array([[1, 8, 5, ..., 1.4, 1.74, 0],
       [1, 6, 1, ..., -0.3, 0.79, 2],
       [1, 1, 5, ..., 1.4, 1.74, 0],
       ...,
       [1, 1, 1, ..., -0.3, 0.79, 0],
       [1, 1, 1, ..., -0.8, -3.12, 2],
       [1, 5, 1, ..., 3.7, -1.7, 2]], dtype=object)

In [ ]:
#use of onehot encoder to encode all this
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# creating a ColumnTransformer named ct that uses OneHotEncoder to encode categorical features in column 34, while passing through the other columns.
ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [34])], remainder ="passthrough")

In [ ]:
#iloc is used for integer-location based indexing.
#[:, 0:34] selects all rows and columns from 0 to 33 (inclusive) for features.
#[:, 34] selects all rows from column 34 for the label.

X = df[:,0:34]
y = df[:,34]

In [ ]:

#fit_transform:

#The fit_transform method is used to both fit the transformer (learn any necessary parameters) and apply the transformation in a single step.
#In this case, it will apply the transformations specified in the ColumnTransformer to the entire DataFrame.

#Result (y):
#The transformed data is stored in the variable y.
#The structure and content of y depend on the transformations specified in the ColumnTransformer.

y=ct.fit_transform(df)


the ColumnTransformer is specified to apply StandardScaler to numerical columns and OneHotEncoder to categorical columns. The resulting y would be the transformed data. Adjust the transformer specifications based on the types of columns in your DataFrame and the preprocessing steps you want to apply.

In [ ]:
#displaying  the transformed data
y

array([[1.0, 0.0, 0.0, ..., 10.8, 1.4, 1.74],
       [0.0, 0.0, 1.0, ..., 13.9, -0.3, 0.79],
       [1.0, 0.0, 0.0, ..., 10.8, 1.4, 1.74],
       ...,
       [1.0, 0.0, 0.0, ..., 13.9, -0.3, 0.79],
       [0.0, 0.0, 1.0, ..., 9.4, -0.8, -3.12],
       [0.0, 0.0, 1.0, ..., 12.7, 3.7, -1.7]], dtype=object)

In [ ]:
Y=pd.DataFrame(y)
Y.head(2)


0    1    2  3  4  5   6  7  8  9   ... 27 28 29 30 31         32 33  \
0  1.0  0.0  0.0  1  8  5   2  1  1  1  ...  0  0  0  0  0        0.0  0   
1  0.0  0.0  1.0  1  6  1  11  1  1  1  ...  0  0  6  6  6  13.666667  0   

     34   35    36  
0  10.8  1.4  1.74  
1  13.9 -0.3  0.79  

[2 rows x 37 columns]

In [ ]:
#splitting the data into training and testing

from sklearn.model_selection import train_test_split
x_train,X_test,y_train,Y_test = train_test_split(X , y , test_size =0.2 ,random_state = 0 )

In [ ]:
#fitting multiple linear regression to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [ ]:
#predicting for results
y_pred = regressor.predict(X_test)
y_pred

array([[ 2.35674577e-01,  2.58120566e-01,  5.06204857e-01, ...,
         9.40000000e+00, -8.00000000e-01, -3.12000000e+00],
       [ 8.10245430e-01,  3.26371856e-01, -1.36617286e-01, ...,
         1.08000000e+01,  1.40000000e+00,  1.74000000e+00],
       [ 1.28925282e-02,  9.05557271e-02,  8.96551745e-01, ...,
         1.08000000e+01,  1.40000000e+00,  1.74000000e+00],
       ...,
       [ 1.46741932e-01,  4.54106632e-02,  8.07847405e-01, ...,
         1.27000000e+01,  3.70000000e+00, -1.70000000e+00],
       [-3.59018371e-02,  1.10923069e-01,  9.24978768e-01, ...,
         9.40000000e+00, -8.00000000e-01, -3.12000000e+00],
       [ 2.38381693e-01,  1.40020425e-01,  6.21597882e-01, ...,
         1.39000000e+01, -3.00000000e-01,  7.90000000e-01]])

In [ ]:
#calculating coefficients and intercepts
print(regressor.coef_)

[[-9.32638927e-03 -1.47045995e-04  9.24848808e-03 ...  6.93270323e-03
  -2.07078979e-03  1.56892002e-03]
 [ 8.97786831e-03  2.67391044e-03 -7.71491160e-03 ... -7.19080617e-03
  -2.63646214e-03 -5.46242738e-03]
 [ 3.48520962e-04 -2.52686444e-03 -1.53357649e-03 ...  2.58102944e-04
   4.70725193e-03  3.89350737e-03]
 ...
 [-2.75030687e-16  4.85722573e-16 -1.56101922e-16 ...  1.00000000e+00
  -4.84613850e-16  9.84116759e-17]
 [-6.77655330e-17 -1.07119175e-16  3.20917571e-16 ... -1.22791524e-16
   1.00000000e+00 -1.40958988e-16]
 [-5.29782170e-16 -3.13117587e-16  4.44476122e-17 ...  2.42179560e-16
   5.11805759e-17  1.00000000e+00]]


Each coef_featureX represents the coefficient for the corresponding feature in your dataset. These coefficients indicate the impact of each feature on the predicted outcome. Positive coefficients suggest a positive correlation, while negative coefficients suggest a negative correlation.

For example, if you have a coefficient of 3 for feature1, it means that, holding other features constant, a one-unit increase in feature1 is associated with a 3-unit increase in the predicted outcome.

Keep in mind that the interpretation of coefficients depends on the context of your specific regression problem and the scaling of your features.








In [ ]:
print(regressor.intercept_)

[ 4.58235984e-01  1.24555376e-01  4.17208641e-01  5.55111512e-15
 -8.88178420e-16 -2.22044605e-16 -3.55271368e-15 -4.44089210e-16
  5.77315973e-15  6.66133815e-16 -2.66453526e-14 -7.10542736e-15
  1.77635684e-15  1.33226763e-14  1.33226763e-15 -1.45716772e-15
 -1.06858966e-15  2.77555756e-15  5.55111512e-17  2.77555756e-16
 -2.48689958e-14  2.42861287e-16 -7.21644966e-15 -6.21724894e-15
 -1.77635684e-15  8.88178420e-16  1.77635684e-14  2.77555756e-17
 -3.77475828e-15  8.88178420e-15  1.77635684e-15  3.55271368e-15
  1.42108547e-14  7.21644966e-16  7.10542736e-15  1.77635684e-15
 -2.86576318e-15]


The intercept_value is a constant term that is added to the weighted sum of the features to obtain the final predicted outcome. In a simple linear regression with one feature, it represents the y-intercept of the regression line.

For example, if the intercept is 2.5, it means that when all the features are zero, the predicted outcome is 2.5. The coefficients of the features (obtained from regressor.coef_) then represent how much the predicted outcome changes for a one-unit change in each feature.

Understanding the intercept and coefficients is crucial for interpreting the results of a linear regression model and making predictions based on new input data.

In [ ]:
#calculating the R squared value
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)

0.9514743885647828